version: '3.6'

services:  
  ##
  ## Frontend
  ##
  frontendjoe:
    restart: always
    image: discretezoo/mbgen-frontend:joe
    
    environment:
      REACT_APP_ZOOAPI: https://${JOE_DZ_API_DOMAIN}

      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${JOE_DZ_DOMAIN}
      LETSENCRYPT_HOST: ${JOE_DZ_DOMAIN}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}

  frontendmath:
    restart: always
    image: discretezoo/mbgen-frontend:mathilde
    
    environment:
      REACT_APP_ZOOAPI: https://${MATH_DZ_API_DOMAIN}

      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${MATH_DZ_DOMAIN}
      LETSENCRYPT_HOST: ${MATH_DZ_DOMAIN}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}
  
  frontendjane:
    restart: always
    image: discretezoo/mbgen-frontend:jane
    
    environment:
      REACT_APP_ZOOAPI: https://${JANE_DZ_API_DOMAIN}

      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${JANE_DZ_DOMAIN}
      LETSENCRYPT_HOST: ${JANE_DZ_DOMAIN}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}
  
  ##
  ## Backends
  ##
  backendjoe:
    restart: always
    image: discretezoo/mbgen-backend:joe

    environment:
      ZOODB_JDBC: "jdbc:postgresql://db:5432/${DZ_USER}"
      ZOODB_USER: ${DZ_USER}
      ZOODB_PASS: ${DZ_PASSWORD}

      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${JOE_DZ_API_DOMAIN}
      LETSENCRYPT_HOST: ${JOE_DZ_API_DOMAIN}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}

  backendmath:
    restart: always
    image: discretezoo/mbgen-backend:mathilde
    environment:
      ZOODB_JDBC: "jdbc:postgresql://db:5432/${DZ_USER}"
      ZOODB_USER: ${DZ_USER}
      ZOODB_PASS: ${DZ_PASSWORD}

      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${MATH_DZ_API_DOMAIN}
      LETSENCRYPT_HOST: ${MATH_DZ_API_DOMAIN}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}
  
  backendjane:
    restart: always
    image: discretezoo/mbgen-backend:jane

    environment:
      ZOODB_JDBC: "jdbc:postgresql://db:5432/${DZ_USER}"
      ZOODB_USER: ${DZ_USER}
      ZOODB_PASS: ${DZ_PASSWORD}

      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${JANE_DZ_API_DOMAIN}
      LETSENCRYPT_HOST: ${JANE_DZ_API_DOMAIN}
      LETSENCRYPT_EMAIL: ${LE_EMAIL}

networks:
  default:
    external:
      name: web-deploy_dzinternal